name = "astro-brochure-worker"
main = "dist/_worker.js"
compatibility_date = "2025-08-01"

kv_namespaces = [
  { binding = "EDGE_STORE", id = "REPLACE_WITH_DEV_KV_ID" }
]

[env.prod]
kv_namespaces = [
  { binding = "EDGE_STORE", id = "REPLACE_WITH_PROD_KV_ID" }
]